server:
    port: 8000
    host: 0.0.0.0
    CALLBACK_SERVER:
        host: "http://dev-api.foresightx.com.cn/foresightx-ai-pet"
        url: "/v1/recognize/result/callback"
        method: "POST"
    VLLM_CHAT_SERVER:
        host: "http://10.1.0.222:8080"
        url: "/v1/chat/completions"
        method: "POST"
        model_name:  "qwen2.5-72b"
        api_key: "*"
    VLLM_IMAGE_SERVER:
        host: "http://10.1.0.216:8020"
        url: "/v1/chat/completions"
        method: "POST"
        model_name:  "Qwen2.5-VL-72B-Instruct"
        api_key: "*"
logger:
  level: INFO
  log_file: /var/log/petpal/app.log
  when: midnight       # 按天分割日志
  backup_count: 7      # 保留最近 7 天的日志
  format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"