server:
    port: 8000
    host: 0.0.0.0
    CALLBACK_SERVER:
        url: "http://dev-api.foresightx.com.cn/foresightx-ai-pet"
        method: "POST"
    VLLM_CHAT_SERVER:
        url: "http://10.1.0.222:8080/v1/chat/completions"
        method: "POST"
    VLLM_IMAGE_SERVER:
        url: "http://10.1.0.216:8020/v1/chat/completions"
        method: "POST"