services:
  agent-service:
    container_name: agent-service
    build: .
    image: ding/pets/agent-service-py11:v1.0.1
    privileged: true
    ipc: host
    shm_size: "80gb"
    working_dir: /workspace
    volumes:
      - /var/log/petpal:/workspace/log
    entrypoint: []
    environment:
      - MTHREADS_VISIBLE_DEVICES=all
    command:
      - /bin/bash
      - -c
      - |
        python main.py --port  8000 || tail -f /dev/null
    ports:
      - "8010:8000"
    networks:
      - docker_ragflow


networks:
  docker_ragflow:
    external: true